import type { Metadata } from "next";
import "../style/globals.css";

export const metadata: Metadata = {
	title: "Safin Ali",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>

				<section>
					<main className={`overflow-hidden`}>
						{ children }
					</main>
				</section>
			</body>
		</html>
	);
}
