import type { Metadata } from "next";
import "../style/globals.css";
import Navbar from '@/components/CSR/Navbar/Navbar';
import { Inter,Montserrat,Roboto,Lato,Raleway,Nunito } from 'next/font/google'
import Mobile_Navbar from '@/components/CSR/Navbar/Mobile_Navbar';

export const metadata: Metadata = {
	title: "Safin Ali",
	description: "Generated by create next app",
};

export const inter = Nunito({
	weight:['200','300','400','500','600','700','800', '900'],
	subsets: ['latin'],
	fallback:['system-ui', 'arial'],
	display: 'swap',
})

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className}`}>

				<>
					<main className={`h-full`}>
						{ children }
					</main>
					{/* navigation route */ }
					<div className={ `hidden md:block md:absolute md:bottom-2 lg:bottom-[7%] md:right-[5%]` }>
						<Navbar />
					</div>

					{/* mobile navigation route */ }
					<div className={ `block md:hidden w-full absolute bottom-0 right-0` }>
						<Mobile_Navbar/>
					</div>

					{/* gradient background */ }
					<div>

						{/* blob 1 */ }
						<div className={'fixed left-1/2 -top-[20%] transform -translate-x-1/2 blur-3xl opacity-50 -z-[1]'}>
							<svg
								xmlns="http://www.w3.org/2000/svg"
								viewBox="15.06 24.96 153.37 141.66"
								className={'w-72 fill-pink-600/35'}
							>
								<path
									fill="inherit"
									d="M115.6 62.7c4.1 12.6 6.4 17.9 14.4 22.9 7.9 5 21.6 9.7 29.6 19.1 8.1 9.3 10.7 23.3 7.5 36.6s-12.1 25.9-24.3 25.3c-12.1-.7-27.4-14.5-40.3-18.8-12.8-4.3-23.2.8-35.4 1.5-12.3.7-26.4-3.1-37.1-12.1s-18.1-23.1-13.6-34.6C21 91.1 37.5 82.3 48.1 73.1 58.7 64 63.5 54.6 71.2 44s18.2-22.3 26.4-18.2c8.2 4.2 13.9 24.2 18 36.9"
								/>
							</svg>
						</div>

						{/* blob 2 */ }
						<div className={'fixed right-0 top-1/2 transform -translate-y-1/2 blur-3xl opacity-40 -z-[1]'}>
							<svg
								xmlns="http://www.w3.org/2000/svg"
								viewBox="36.91 13.47 123.75 163.21"
								className={'w-72 fill-indigo-700/35'}
							>
								<path
									fill="inherit"
									d="M41.9,-74.6C53.4,-65.8,61.5,-53,60.6,-39.9C59.8,-26.8,50.1,-13.4,48.7,-0.8C47.4,11.8,54.5,23.7,55.2,36.7C56,49.7,50.5,63.8,40.3,70.6C30,77.5,15,77,0.4,76.3C-14.2,75.6,-28.3,74.6,-35,65.7C-41.6,56.8,-40.7,39.9,-45.2,27.6C-49.7,15.3,-59.7,7.7,-62.3,-1.5C-65,-10.7,-60.3,-21.4,-55,-32.3C-49.7,-43.2,-43.7,-54.3,-34.4,-64.4C-25.2,-74.6,-12.6,-83.8,1.3,-86C15.1,-88.2,30.3,-83.4,41.9,-74.6Z"
									transform="translate(100 100)"
								/>
							</svg>
						</div>

						{/* blob 3 */ }
						<div className={'fixed -bottom-[30%] rotate-[40deg] blur-3xl opacity-40 -z-[1]'}>
							<svg
								xmlns="http://www.w3.org/2000/svg"
								viewBox="31.63 27.25 118.52 159.69"
								className={'w-72 fill-green-600/35'}
							>
								<path
									fill="inherit"
									d="M34.6,-53.8C40.9,-42.9,39.5,-27.7,40.2,-15.4C41,-3.2,43.8,6,46.8,21C49.8,36,53.1,56.8,45.4,70.5C37.6,84.2,18.8,90.7,4.4,84.7C-10,78.6,-20.1,60,-33.6,48.2C-47.2,36.4,-64.3,31.4,-67.7,21.8C-71.1,12.2,-60.8,-2.1,-55.3,-17.6C-49.7,-33,-48.9,-49.7,-40.5,-59.9C-32.1,-70,-16.1,-73.8,-1,-72.5C14.1,-71.1,28.2,-64.7,34.6,-53.8Z"
									transform="translate(100 100)"
								/>
							</svg>
						</div>
					</div>
				</>
			</body>
		</html>
	);
}
