import type { Metadata } from "next";
import "../style/globals.css";
import Navbar from '@/components/CSR/Navbar/Navbar';

export const metadata: Metadata = {
	title: "Safin Ali",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>

				<section>
					<main className={ `overflow-hidden` }>
						{ children }
					</main>
					{/* navigation route */ }
					<div className={ `absolute bottom-10 right-[5%]` }>
						<Navbar />
					</div>
				</section>
			</body>
		</html>
	);
}
